# Data Wrangling II
Create an “Academic performance” dataset of students and perform the following operations
using Python.
1. Scan all variables for missing values and inconsistencies. If there are missing values
and/or inconsistencies, use any of the suitable techniques to deal with them.
2. Scan all numeric variables for outliers. If there are outliers, use any of the suitable
techniques to deal with them.
3. Apply data transformations on at least one of the variables. The purpose of this
transformation should be one of the following reasons: to change the scale for better
understanding of the variable, to convert a non-linear relation into a linear one, or to
decrease the skewness and convert the distribution into a normal distribution.
Reason and document your approach properly.

In [10]:
import pandas as pd
import numpy as np

creating dataset using by randomly allocating gender, division, marks and attendance

In [11]:
rollno = np.arange(start=1, stop=101, step=1)
rollno

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
sample_arr = ["M", "F"]
gender= np.random.choice(sample_arr, size=100)
gender

array(['M', 'M', 'F', 'M', 'F', 'M', 'F', 'F', 'M', 'F', 'F', 'F', 'M',
       'M', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'F', 'F', 'F', 'M', 'F',
       'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'F', 'F', 'M', 'F', 'F',
       'M', 'F', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'M', 'M',
       'M', 'M', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'M', 'M', 'M',
       'M', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M',
       'M', 'M', 'F', 'M', 'F', 'F', 'F', 'F', 'M', 'M', 'F', 'M', 'M',
       'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'F'], dtype='<U1')

In [13]:
sample_arr = ["TE1", "TE2", "TE3", "TE4"]
div= np.random.choice(sample_arr, size=100)
div

array(['TE1', 'TE3', 'TE2', 'TE3', 'TE2', 'TE4', 'TE4', 'TE1', 'TE2',
       'TE4', 'TE3', 'TE4', 'TE2', 'TE1', 'TE2', 'TE3', 'TE1', 'TE1',
       'TE2', 'TE4', 'TE3', 'TE1', 'TE2', 'TE3', 'TE2', 'TE1', 'TE3',
       'TE2', 'TE2', 'TE3', 'TE4', 'TE2', 'TE3', 'TE4', 'TE2', 'TE1',
       'TE1', 'TE3', 'TE1', 'TE3', 'TE3', 'TE1', 'TE3', 'TE4', 'TE2',
       'TE2', 'TE1', 'TE3', 'TE2', 'TE2', 'TE2', 'TE2', 'TE3', 'TE1',
       'TE3', 'TE3', 'TE4', 'TE1', 'TE2', 'TE1', 'TE4', 'TE4', 'TE1',
       'TE1', 'TE3', 'TE1', 'TE2', 'TE2', 'TE1', 'TE4', 'TE2', 'TE2',
       'TE1', 'TE3', 'TE3', 'TE1', 'TE4', 'TE3', 'TE1', 'TE3', 'TE2',
       'TE4', 'TE2', 'TE4', 'TE4', 'TE1', 'TE1', 'TE2', 'TE2', 'TE4',
       'TE1', 'TE4', 'TE2', 'TE2', 'TE1', 'TE3', 'TE2', 'TE1', 'TE2',
       'TE1'], dtype='<U3')

In [14]:
marks1 = np.random.randint(low=40, high=95, size=100)
marks1

array([93, 87, 62, 60, 51, 77, 62, 86, 46, 90, 40, 65, 56, 69, 85, 63, 71,
       56, 41, 57, 83, 85, 45, 82, 61, 48, 44, 42, 70, 55, 79, 94, 84, 51,
       55, 74, 91, 91, 58, 59, 81, 88, 67, 75, 44, 46, 71, 56, 53, 61, 76,
       85, 87, 45, 75, 54, 82, 74, 48, 50, 60, 69, 72, 88, 44, 56, 47, 83,
       45, 68, 89, 54, 41, 72, 61, 48, 88, 94, 66, 83, 46, 84, 73, 56, 49,
       48, 73, 60, 58, 61, 84, 63, 79, 93, 43, 42, 64, 55, 91, 73])

In [15]:
marks2 = np.random.randint(low=40, high=95, size=100)
marks2

array([86, 73, 40, 66, 48, 57, 72, 93, 66, 83, 40, 55, 60, 84, 59, 93, 57,
       89, 60, 89, 81, 45, 65, 84, 65, 45, 53, 89, 58, 55, 85, 54, 44, 49,
       90, 72, 89, 69, 69, 44, 76, 71, 67, 45, 41, 86, 75, 66, 42, 92, 76,
       74, 68, 43, 45, 44, 81, 47, 85, 46, 77, 82, 89, 77, 52, 93, 83, 47,
       46, 61, 52, 53, 72, 49, 92, 71, 68, 77, 83, 91, 61, 56, 84, 68, 60,
       70, 83, 63, 64, 94, 94, 76, 88, 43, 43, 89, 40, 66, 82, 93])

In [16]:
marks3 = np.random.randint(low=40, high=95, size=100)
marks3

array([40, 91, 59, 68, 67, 92, 92, 43, 53, 76, 43, 89, 55, 50, 77, 58, 72,
       69, 73, 49, 59, 82, 51, 86, 47, 42, 74, 45, 94, 84, 41, 44, 73, 60,
       89, 87, 49, 45, 57, 48, 80, 69, 68, 44, 63, 51, 79, 75, 60, 84, 69,
       71, 89, 45, 83, 67, 90, 81, 69, 69, 73, 85, 40, 83, 42, 80, 43, 68,
       79, 78, 71, 43, 54, 91, 46, 75, 57, 50, 94, 62, 85, 56, 73, 94, 83,
       69, 52, 44, 64, 43, 71, 86, 67, 42, 57, 88, 61, 64, 76, 44])

In [17]:
attendance=np.random.uniform(low=40.0, high=95.0, size=(100))
attendance = np.round(attendance, decimals=2)
attendance

array([68.46, 60.06, 61.77, 43.98, 86.39, 40.17, 91.28, 74.45, 91.89,
       82.38, 49.96, 68.03, 71.27, 74.24, 66.15, 48.5 , 94.29, 40.62,
       89.69, 48.07, 89.42, 89.6 , 60.57, 74.45, 79.58, 55.43, 90.98,
       65.98, 51.49, 40.18, 71.5 , 42.28, 42.8 , 63.01, 70.29, 85.46,
       84.98, 64.21, 72.81, 53.02, 68.83, 63.85, 62.54, 66.29, 78.71,
       76.  , 63.  , 54.23, 72.33, 55.83, 49.51, 78.27, 43.22, 80.34,
       71.51, 84.85, 82.7 , 63.82, 70.38, 72.27, 67.7 , 50.45, 45.54,
       41.25, 90.92, 77.35, 66.02, 49.36, 69.3 , 53.34, 67.85, 84.16,
       54.17, 48.38, 80.26, 57.54, 49.33, 72.78, 48.93, 60.15, 70.65,
       43.48, 44.26, 89.3 , 60.66, 55.55, 72.55, 86.03, 81.98, 74.8 ,
       63.2 , 78.27, 73.67, 63.18, 86.21, 78.97, 62.6 , 87.32, 82.65,
       46.75])

In [18]:
dic = {
    'roll_no': rollno,
    'gender': gender,
    'sub1': marks1,
    'sub2': marks2,
    'sub3': marks3,
    'attendance': attendance
}

converting above data into a dataframe 

In [19]:
df  = pd.DataFrame(dic)

In [20]:
df

roll_no gender  sub1  sub2  sub3  attendance
0         1      M    93    86    40       68.46
1         2      M    87    73    91       60.06
2         3      F    62    40    59       61.77
3         4      M    60    66    68       43.98
4         5      F    51    48    67       86.39
..      ...    ...   ...   ...   ...         ...
95       96      M    42    89    88       78.97
96       97      M    64    40    61       62.60
97       98      M    55    66    64       87.32
98       99      F    91    82    76       82.65
99      100      F    73    93    44       46.75

[100 rows x 6 columns]

In [21]:
cols = ['sub1', 'sub2', 'sub3']
df['avg']=df[cols].mean(axis=1)
df

roll_no gender  sub1  sub2  sub3  attendance        avg
0         1      M    93    86    40       68.46  73.000000
1         2      M    87    73    91       60.06  83.666667
2         3      F    62    40    59       61.77  53.666667
3         4      M    60    66    68       43.98  64.666667
4         5      F    51    48    67       86.39  55.333333
..      ...    ...   ...   ...   ...         ...        ...
95       96      M    42    89    88       78.97  73.000000
96       97      M    64    40    61       62.60  55.000000
97       98      M    55    66    64       87.32  61.666667
98       99      F    91    82    76       82.65  83.000000
99      100      F    73    93    44       46.75  70.000000

[100 rows x 7 columns]

can be converted into a csv file using:

In [22]:
df.to_csv("My_student_dataset.csv")